name: Sync to Production Repositories

on:
  push:
    branches:
      - ie20935

  # Permite la ejecución manual para pruebas
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "SIASIS IE20935 Sync Bot"
          git config --global user.email "siasis-sync@asuncion8.edu.pe"

      # Repositorio 1
      - name: Push to Repository 1
        run: |
          git remote add repo1 https://x-access-token:${{ secrets.SIU01_INS1_REPOSITORIO_PRODUCCION_TOKEN }}@github.com/SIU01-ASUNCION8-SIASIS/SIU01-INS1-IE20935.git
          git push repo1 ie20935:master
        continue-on-error: true
